# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

In [0]:
#!pip list

In [0]:
#!pip install -U tensorflow==2.0

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


## Importing Google Drive Libraries

### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import numpy as np
import pandas as pd
import sklearn.datasets as ds
from sklearn.model_selection import train_test_split

In [0]:
data = ds.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
features = data.data
target = data.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.25, random_state=42)

In [0]:
X_train[0:10]

array([[5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8]])

In [0]:
y_train[0:10]

array([0, 0, 2, 1, 1, 0, 0, 1, 2, 2])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from keras import utils

Using TensorFlow backend.


In [0]:
y_train_ohe = utils.to_categorical(y_train, num_classes=3, dtype=int)
y_test_ohe = utils.to_categorical(y_test, num_classes=3, dtype=int)

In [0]:
y_train_ohe[0:10]

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow import keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

In [0]:
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add one Input Layer
model.add(Dense(10, activation='softmax', input_shape=(4,)))
# Add one hidden layer 
model.add(Dense(5, activation='softmax'))
# Add an output layer 
model.add(Dense(3, activation='softmax'))

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 18        
Total params: 123
Trainable params: 123
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 18        
Total params: 123
Trainable params: 123
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
model.fit(X_train, y_train_ohe,epochs=100,verbose=1, validation_data=(X_test, y_test_ohe))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 1s 6ms/sample - loss: 1.1122 - accuracy: 0.3125 - val_loss: 1.0906 - val_accuracy: 0.3947
Epoch 2/100
112/112 [==============================] - 0s 209us/sample - loss: 1.1116 - accuracy: 0.3125 - val_loss: 1.0904 - val_accuracy: 0.3947
Epoch 3/100
112/112 [==============================] - 0s 151us/sample - loss: 1.1110 - accuracy: 0.3125 - val_loss: 1.0903 - val_accuracy: 0.3947
Epoch 4/100
112/112 [==============================] - 0s 162us/sample - loss: 1.1102 - accuracy: 0.3125 - val_loss: 1.0902 - val_accuracy: 0.3947
Epoch 5/100
112/112 [==============================] - 0s 160us/sample - loss: 1.1097 - accuracy: 0.3125 - val_loss: 1.0900 - val_accuracy: 0.3947
Epoch 6/100
112/112 [==============================] - 0s 153us/sample - loss: 1.1090 - accuracy: 0.3125 - val_loss: 1.0899 - val_accuracy: 0.3947
Epoch 7/100
112/112 [==============================] - 0s 189us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_predict = model.predict(X_test)

In [0]:
y_predict[0]

array([0.32377636, 0.34223548, 0.3339881 ], dtype=float32)

In [0]:
print("Predicted Label for Row#0 : ",np.argmax(y_predict[0]))

Predicted Label for Row#0 :  1


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
print("Actual Label for Row#0 : ",np.argmax(y_test[0]))

Actual Label for Row#0 :  0




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
#%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [4]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)
#tf.random.set_random_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

**Loading the data from Google Drive**

In [10]:
stock_link = 'https://drive.google.com/open?id=1lTeyKbt4uc9X3BDppnFX1mYBmaEfMZws'
fluff, stock_id = stock_link.split('=')
print (stock_id) 
downloaded_stock = drive.CreateFile({'id':stock_id})
downloaded_stock.GetContentFile('prices.csv')  
df_stock = pd.read_csv('prices.csv')

1lTeyKbt4uc9X3BDppnFX1mYBmaEfMZws


In [11]:
df_stock.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [12]:
df_stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df_new_stock = df_stock.drop(labels=['date','symbol'],axis=1)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
df_limited_stock = df_new_stock[0:1000]

In [15]:
df_limited_stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
open      1000 non-null float64
close     1000 non-null float64
low       1000 non-null float64
high      1000 non-null float64
volume    1000 non-null float64
dtypes: float64(5)
memory usage: 39.2 KB


## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
df_features = df_limited_stock[['open','close','low','high']]
df_labels = df_limited_stock[['volume']]

In [41]:
df_features.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

In [42]:
df_labels.head()

volume
0  2163600.0
1  2386400.0
2  2489500.0
3  2006300.0
4  1408600.0

Normalizing the label column by dividing it with 1000000

In [0]:
df_labels = df_labels/1000000

In [20]:
df_labels.head()

volume
0  2.1636
1  2.3864
2  2.4895
3  2.0063
4  1.4086

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [44]:
features_stock = np.array(df_features)
features_stock = np.float32(features_stock)
print(features_stock.dtype)

labels_stock = np.array(df_labels)
labels_stock = np.float32(labels_stock)
print(labels_stock.dtype)

float32
float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [45]:
features_l2_norm = tf.math.l2_normalize(features_stock, axis=None, epsilon=1e-12, name=None)
features_l2_norm.dtype

tf.float32

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

In [47]:
print(W)
print(b)

tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def predictor(features, W, b):
  y_pred = tf.add(tf.matmul(features, W), b)
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y_actual, y_predicted):
  return tf.reduce_mean(tf.square(y_actual - y_predicted))

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X, y_actual, W, b, learning_rate=0.01):
  with tf.GradientTape() as tape:
    tape.watch([W,b])
    curr_prediction = predictor(X, W, b)
    curr_loss = loss(y_actual, curr_prediction)

  #evalute the gradient with the respect to the paramters
  dW, db = tape.gradient(curr_loss, [W, b])

  W = W - learning_rate * dW
  b = b - learning_rate * db

  return W,b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [51]:
for i in range(100):
  #W, b = train(features_l2_norm, labels_l2_norm, W, b)
  W, b = train(features_l2_norm, labels_stock, W, b)

  if i % 10 == 0:
    print("Step {:03d}: Loss {:.6f}: ".format(i, loss(labels_stock, predictor(features_l2_norm, W, b)).numpy()))

print(f'W : {W.numpy()} , b  = {b.numpy()} ')

Step 000: Loss 236.168045: 
Step 010: Loss 227.151093: 
Step 020: Loss 221.132523: 
Step 030: Loss 217.115234: 
Step 040: Loss 214.433716: 
Step 050: Loss 212.643753: 
Step 060: Loss 211.448868: 
Step 070: Loss 210.651215: 
Step 080: Loss 210.118546: 
Step 090: Loss 209.762939: 
W : [[0.0194333 ]
 [0.01969694]
 [0.01937149]
 [0.01976266]] , b  = [4.608607] 


### Observe values of Weight
- Print the updated values

In [52]:
print(f'Weight : {W.numpy()} ')

Weight : [[0.0194333 ]
 [0.01969694]
 [0.01937149]
 [0.01976266]] 


### Observe values of Bias
- Print the updated values

In [53]:
print(f'Bias  = {b.numpy()} ')

Bias  = [4.608607] 
